# Generated by Django 2.2.6 on 2019-11-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='player',
            name='lname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=256),
        ),
    ]
