# Generated by Django 2.2.6 on 2019-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191205_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fldGoalAtt',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='log',
            name='fldGoalMade',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
