# Generated by Django 2.2.6 on 2019-12-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191205_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fldGoalAtt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='fldGoalMade',
            field=models.FloatField(),
        ),
    ]
