# Generated by Django 2.2.6 on 2019-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191205_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='threePtAtt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='threePtMade',
            field=models.FloatField(),
        ),
    ]
